### ISSUE TITLE
如何存储用户阅读进度

### ISSUE THREAD

**Issue by buzai** [Andyliwr/mbook#13]
在用户离开的时候调用接口，直接存储看哪本书到哪个章节了，并且发送到数据库，每次进来请求获取数据，并且和本地的数据对比，直接跳转最新的那个章节我觉的就好了，还有你们这个页面只能在微信用吗

**Comment by buzai** [comment]
还有就是小说是收费的你们都能破了？还说你们只是抓取的免费章节

**Comment by dkvirus** [comment]
同上所问，最近追的有本小说就是收费的.....

**Comment by Andyliwr** [comment]
@buzai 不好意思，我当时应该在github的提示邮件里直接回复你了，我以为也回答的文字会直接显示在issue上的，没想到没有。
现在对你们问的做系统些的回答。
**问题1：关于如何存储用户进度的问题**
我当时实现的后台还没有实现记录用户阅读进度的接口，所以只是将进度存储到了本地。你提出的方案我觉是合理的。
**问题2：页面只能在微信里用吗？**
微书的前端实现是基于微信小程序的，所以也限制了它的使用场景只能是微信里。
**问题3：能否破解收费小说？**
小编还年轻，不想被警察叔叔请去喝茶。人家的内容之所以收费，是因为人家拥有知识产权。所以原则上微书不会提供收费小说的阅读。

**Comment by Simmon12** [comment]
请问怎么运行爬虫的程序？
