### ISSUE TITLE
兄弟有空更新一下代码吧，哪怕能跑就行....

### ISSUE THREAD

**Issue by EarlyBedEarlyUp** [Andyliwr/mbook#24]
运行调试了一个月，发现很多东西都没做好，个人信息页面的那些文字都是静态的，node爬虫规则也早就无法正常运行了，哎，本来想节约时间的才下这个来改，最后用的时间比自己做还长。

**Comment by Andyliwr** [comment]
更新了，可以参照readme再试试 @EarlyBedEarlyUp
